blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

ecommerce_prj/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.db.models.signals import post_save
from django.utils.html import mark_safe
from django_ckeditor_5.fields import CKEditor5Field


from PIL import Image
from shortuuid.django_fields import ShortUUIDField

IDENTITY_TYPE = (
    ("national_id_card", "National ID Card"),
    ("drivers_licence", "Drives Licence"),
    ("international_passport", "International Passport")
)

GENDER = (
    ("femail", "Female"),
    ("male", "Male"),
)


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.user.id, ext)
    return 'user_{0}/{1}'.format(instance.user.id,  filename)

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    roles = models.CharField(max_length=100, null=True, blank=True)
    total_spent = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    billing_first_name = models.CharField(max_length=500, null=True, blank=True)
    billing_last_name = models.CharField(max_length=500, null=True, blank=True)
    billing_email = models.CharField(max_length=500, null=True, blank=True)
    billing_phone = models.CharField(max_length=500, null=True, blank=True)
    billing_address = models.CharField(max_length=500, null=True, blank=True)
    billing_state = models.CharField(max_length=500, null=True, blank=True)
    billing_country = models.CharField(max_length=500, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    # def save(self, *args, **kwargs):
    #     if self.roles == "wcfm_vendor":
    #         "vendor.Vendor".objects.create(user=self, profile=None)
    #     else:
    #         self.product.status = "published"
    #         self.product.save()
            
    #     super(User, self).save(*args, **kwargs) 



class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz123")
    cover_image = models.ImageField(upload_to=user_directory_path, default="cover.jpg", blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, default="default.jpg", null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=1000, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    about_me = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, null=True, blank=True)


    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    postal_code = models.CharField(max_length=1000, null=True, blank=True)
    
    identity_type = models.CharField(choices=IDENTITY_TYPE, default="national_id_card", max_length=100, null=True, blank=True)
    identity_image = models.ImageField(upload_to=user_directory_path, default="id.jpg", null=True, blank=True)

    facebook = models.URLField(default="https://facebook.com/", null=True, blank=True)
    instagram = models.URLField(default="https://instagram.com/", null=True, blank=True)
    twitter = models.URLField(default="https://twitter.com/", null=True, blank=True)
    whatsApp = models.CharField(default="+123 (456) 789", max_length=100, blank=True, null=True)

    verified = models.BooleanField(default=False)
    seller = models.BooleanField(default=False)
    subscribed_newsletter = models.BooleanField(default=False)

    referral_earning = models.DecimalField(default=0.00, decimal_places=2, max_digits=12)
    wallet = models.DecimalField(default=0.00, decimal_places=2, max_digits=12)

    account_number = ShortUUIDField(length=10, max_length=25, alphabet="1234567890")
    pin = ShortUUIDField(length=4, max_length=6, alphabet="1234567890")
    code = models.CharField(max_length=12, blank=True, null=True)
    recommended_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='ref_by')
    
    saved_product = models.ManyToManyField("store.Product",blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if self.full_name:
            return f"{self.full_name}"
        else:
            return f"{self.user.username}"


    # def save(self, *args, **kwargs):
    #     img = Image.open(self.image.path)
    #     if img.height > 700 or img.width > 700:
    #         output_size = (700, 700)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    #     super().save(*args, **kwargs)

    
    def profile_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" />' % (self.image))

    
    
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)






# class User(AbstractUser):
#     email = models.EmailField(null=True, blank=True)
#     username = models.CharField(max_length=100, null=True, blank=True)
#     full_name = models.CharField(max_length=100, null=True, blank=True, unique=True)
#     bio = models.CharField(max_length=100, null=True, blank=True)
#     roles = models.CharField(max_length=100, null=True, blank=True)
#     total_spent = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
#     billing_first_name = models.CharField(max_length=500, null=True, blank=True)
#     billing_last_name = models.CharField(max_length=500, null=True, blank=True)
#     billing_email = models.CharField(max_length=500, null=True, blank=True)
#     billing_phone = models.CharField(max_length=500, null=True, blank=True)
#     billing_address = models.CharField(max_length=500, null=True, blank=True)
#     billing_state = models.CharField(max_length=500, null=True, blank=True)
#     billing_country = models.CharField(max_length=500, null=True, blank=True)

#     USERNAME_FIELD = "full_name"
#     REQUIRED_FIELDS = ['username']

#     def __str__(self):
#         return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile
from django.forms import ImageField, FileInput
from django.contrib.auth import get_user_model
# from captcha.fields import CaptchaField


class DateInput(forms.DateInput):
    input_type = "date"

class StaffCreationForm(forms.ModelForm):
    
    class Meta:
        model = get_user_model()
        fields = "__all__"
        widgets = {
            'date_joined': DateInput(),
            'last_login': DateInput(),
        }

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Full Name'}), max_length=100, required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Username'}), max_length=100, required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control' , 'id': "", 'placeholder':'Email Address'}), required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'btn__btn__btn form-control' , 'id': "", 'placeholder':'Password'}), required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={ 'class': 'btn__btn__btn form-control' , 'id': "", 'placeholder':'Confirm Password'}), required=False)
    # captcha=CaptchaField()
    
    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'password1', 'password2']
       


class ProfileUpdateForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Full Name', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Residential Address', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'City', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    state = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'State', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    country = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Country', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    gender = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Male / Female', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Mobile Number', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    image = ImageField(widget=FileInput)
    
    class Meta:
        model = Profile
        fields = ['full_name', 'image' ,'gender','address', 'city' , 'state', 'country' , 'phone' ]
        widgets = {
            'image': FileInput(attrs={'id': 'loadFile(event)'}),
            'identity_image': FileInput(attrs={'id': 'preview_id()'}),
        }

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Username', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Enter Email', 'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

templates/userauths/password-reset/change-password.html

{% extends "partials/base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>



<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
        
        {% if form.errors %}
            
            
        <div class="alert alert-danger">
            <strong>{{form.errors}}</strong>
        </div>
        {% endif %}

      <div class="log_reg_form mt70-992">
        <h2 class="title">Change Password</h2>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">New Password</label>
              <br>
              {{form}}
            </div>
            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Save New Password</button>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/check_email.html

{% extends "partials/base.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
      <div class="log_reg_form mt70-992">
        <h2 class="title">Email Sent <i class="fas fa-check-circle"></i></h2>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">Check your email address and follow the instruction to reset your password</label>
            </div>
            
            <a href="{% url 'store:home' %}" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Go Home</a>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset.html

{% extends "partials/base.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
      <div class="log_reg_form mt70-992">
        <h2 class="title">Password Reset</h2>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">Email address</label>
              <br>
              {{form.email}}
            </div>
            
            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Reset Password</button>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_complete.html

{% extends "partials/base.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
      <div class="log_reg_form mt70-992">
        <h3 class="title">Password Reset Successfull. <i class="fas fa-check-circle"></i></h3>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">Congratulations, your password have been reset successfully. You can now login.</label>
            </div>
            
            <a href="{% url 'userauths:sign-in' %}" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Login</a>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_confirm.html

{% extends "partials/base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
      <div class="log_reg_form mt70-992">
        <h2 class="title">Password Reset</h2>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">New Password</label>
              <br>
              {{form}}
            </div>
            
            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Reset Password</button>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_done.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}
  Password Reset Done
{% endblock title %}
{% load humanize %}
{% block content %}


    <!-- Banner Section start -->
    <section class="banner-section inner-banner contact">
        <div class="overlay">
            <div class="shape-area">
                <img src="{% static 'assets/images/contact-illus.png' %}" class="contact-illu" alt="image">
            </div>
            <div class="banner-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9 col-md-10">
                            <div class="main-content">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Banner Section end -->

    <!-- Contact In start -->
    <section class="contact-section">
        <div class="overlay">
            <div class="container bg-area">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div class="section-header text-center">
                            <h2 class="title">Email Sent</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="form-content">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row justify-content-center">
                                    <div class="col-md-12">
                                        <div class="single-input">
                                            <p class="text-center">An email with password reset intructions have been sent to your provided email address.</p>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact In end -->
  
            <!-- register end -->
{% endblock content %}

templates/userauths/password-reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hey, You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}