blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

ecommerce_prj/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager
from userauths.models import user_directory_path
from html import unescape
from django.utils.html import strip_tags
from django_ckeditor_5.fields import CKEditor5Field
from shortuuid.django_fields import ShortUUIDField


User = settings.AUTH_USER_MODEL

BLOG_PUBLISH_STATUS = (
	("draft", "draft"),
	("in_review", "In Review"),
	("published", "Published"),
)


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-id']
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title 
        
    
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to=user_directory_path)
    title = models.CharField(max_length=1000)
    content = CKEditor5Field(config_name='extends')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = TaggableManager()
    status = models.CharField(choices=BLOG_PUBLISH_STATUS, max_length=100, default="in_review")
    featured = models.BooleanField(default=False)
    trending = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    pid = ShortUUIDField(length=10, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz")

    class Meta:
        verbose_name = "Posts"
        verbose_name_plural = "Posts "
    
    def __str__(self):
        return self.title[0:10]

    class Meta:
        ordering = ['-date']

    def get_read_time(self):
        string = self.content + unescape(strip_tags(self.content))
        total_words = len((string).split())

        return round(total_words / 200)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    full_name = models.CharField(max_length=1000)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.comment[0:20]

blog/views.py
from django.shortcuts import redirect, render
from blog.models import Post, Category, Comment
from django.contrib import messages
from django.db.models import Q, Count
from django.core.paginator import Paginator


def blogList(request):
    blog_count = Post.objects.filter(status="published")
    blog = Post.objects.filter(status="published").order_by("-id")
    featured_blog = Post.objects.filter(featured=True, status="published").order_by("-id")[:6]
    categories = Category.objects.filter(active=True)

    query = request.GET.get("q")
    if query:
        blog = blog.filter(
            Q(title__icontains=query)).distinct()

    paginator = Paginator(blog, 15)
    page_number = request.GET.get('page')
    blog = paginator.get_page(page_number)
    
    

    context = {
        "query": query,
        "categories": categories,
        "blog_count": blog_count,
        "blog": blog,
        "featured_blog": featured_blog,
    }
    return render(request, 'blog/post-lists.html', context)

def blogDetail(request, pid):
    post = Post.objects.get(status="published", pid=pid)
    comment = Comment.objects.filter(post=post, active=True)
    blogs = Post.objects.filter(status="published").order_by("-id")[:10]
    related_blogs = Post.objects.filter(category=post.category).order_by("-id")[:12]

    post.views += 1
    post.save()


    if request.method == "POST":
        full_name = request.POST.get("full_name")
        comment = request.POST.get("comment")
        email = request.POST.get("email")

        Comment.objects.create(full_name=full_name, email=email ,comment=comment, post=post)
        messages.success(request, f"Hey {full_name}, your comment have been sent for review.")
        return redirect("blog:blog-detail", post.pid)

    context = {
        "post": post,
        "comment": comment,
        "blogs": blogs,
        "related_blogs":related_blogs
    }
    return render(request, 'blog/post-detail.html', context)


def category_detail(request, slug):
    category = Category.objects.get(slug=slug)
    blog_count = Post.objects.filter(category=category, status="published")
    blog = Post.objects.filter(category=category, status="published")
    categories = Category.objects.filter(active=True)
    
    query = request.GET.get("q")
    if query:
        blog = blog.filter(
            Q(title__icontains=query)).distinct()

    paginator = Paginator(blog, 15)
    page_number = request.GET.get('page')
    blog = paginator.get_page(page_number)
    
    

    context = {
        "blog_count": blog_count,
        "query": query,
        "blog": blog,
        "category": category,
        "categories": categories,
    }
    return render(request, 'blog/category-detail.html', context)

templates/blog/category-detail.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
  
  <section class="inner_page_breadcrumb">
    <div class="container">
      <div class="row">
        <div class="col-xl-6">
          <div class="breadcrumb_content">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="{% url 'blog:blog-list' %}">Blog Posts</a></li>
              <li class="breadcrumb-item"><a href="{% url 'blog:blog-list' %}">Category</a></li>
              <li class="breadcrumb-item active" aria-current="page"><a>{{category.title}}</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

	<section class="blog_post_container pt30 pb80">
		<div class="container">
      <div class="row">
        <div class="col-lg-6 m-auto">
          <div class="main-title text-center">
            
            {% if query == "" or query == None %}
            <h2 class="title">{{category.title}} Category</h2>
            {% else %}
            <h2 class="title">Showing Results for "{{query}}"</h2>
            {% endif %}
                
          </div>
        </div>
      </div>
			<div class="row mt50">
        <div class="col-lg-4 col-xl-3">
          <div class="sidebar_search_widget mb30">
            <form action="" method="GET">
                <div class="blog_search_widget">
                    <div class="input-group">
                      <input name="q" type="text" class="form-control" placeholder="Search Articles..." aria-label="Recipient's username">
                      <button style="border: 1px solid rgba(128, 128, 128, 0.247); background: none;"><i class="fas fa-search"></i></button>
                    </div> 
                  </div>
            </form>
          </div>
          <div class="terms_condition_widget">
            <h4 class="title">Categories</h4>
            <div class="widget_list">
              <ul class="list_details">
                {% for c in categories %}
                    <li><a href="{% url 'blog:category_detail' c.slug %}">{{c.title}}</a></li>
                {% endfor %}
                
              </ul>
            </div>
          </div>
        </div>
				<div class="col-lg-8 col-xl-9">
          <div class="row">
            {% for p in blog %}
            <div class="col-md-6 col-xl-4">
              <div class="for_blog">
                <div class="thumb">
                  <img class="img-whp" src="{{p.image.url}}" style="width: 100%; height: 240px; object-fit: cover;" alt="{{p.title}}">
                </div>
                <div class="details">
                  <div class="tc_content">
                    <span class="subtitle">{{p.category.title}}</span>
                    <h4 class="title"><a href="{% url 'blog:blog-detail' p.pid %}">{{p.title|truncatechars:60}}</a></h4>
                    <span class="post_date">{{p.date|date:"d M, Y"}}</span> <br>
                    <a href="{% url 'blog:blog-detail' p.pid %}" class="purple-btn btn mt-3">Read More</a>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            
          </div>
          <div class="row">
            <div class="col-lg-12">
              <div class="mbp_pagination mt30 text-center">
                <ul class="page_navigation">
                  {% if blog.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="{% url 'blog:blog-list' %}?page={{blog.previous_page_number}}" tabindex="-1" aria-disabled="true"> <span class="fas fa-angle-left"></span></a>
                    </li>
                {% endif %}
                
                {% if blog.has_next %}
                    <li class="page-item">
                    <a class="page-link" href="{% url 'blog:blog-list' %}?page={{blog.next_page_number}}"><span class="fas fa-angle-right"></span></a>
                    </li>
                {% endif %}
                </ul>
                <p class="mt20 pagination_page_count text-center">{{blog_count.count}} Article(s) Found</p>
              </div>
            </div>
          </div>
				</div>
			</div>
		</div>
	</section>

    {% endblock content %}

templates/blog/post-detail.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/default.min.css">
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script src="{% static 'js/prism.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/prism.css' %}">

	<!-- Blog Single Post -->
  <section class="blog_post_container pt0 pb70">
    <div class="container-fluid p0">
      <div class="row">
        <div class="col-lg-12">
          <div class="blog_single_post">
            <div class="thumb">
            <a href="{{post.image.url}}" target="_blank">
                <img class="img-whp" src="{{post.image.url}}" style="height: 200px; object-fit: cover;" alt="24.jpg">
            </a>    
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-10 col-xl-8">
          <div class="main_blog_post_content">
            <div class="blog_single_post">
              <div class="for_blog">
                <div class="details">
                  <div class="tc_content pt30">
                    <span class="subtitle">{{post.category.title}}</span>
                    <h2 class="tiftle">{{post.title}}</h2>
                    <span class="post_date">{{post.date|date:"d M, Y"}}</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="mbp_thumb_post p-4">
              {{post.content|safe}}
            <hr class="mt20">
            <div class="bsp_comments">
              <div class="mbp_first d-flex">
                <div class="flex-shrink-0"> <img src="{{post.user.profile.image.url}}" style="width: 80px; height: 80px; object-fit: cover; border-radius: 50%;" class="mr-3" alt="{{post.user.profile.full_name}}"> </div>
                <div class="flex-grow-1 ms-4">
                  <h4 class="sub_title mb0">{{post.user.profile.full_name}}</h4>
                  <div class="sspd_postdate mb15">{{post.user.profile.bio}}</div>
                  <p>{{ post.user.profile.about_me|safe }}</p>
                </div>
              </div>
            </div>
            <hr>
            <div class="bsp_reveiw_wrt">
                <form class="comments_form" method="POST">
                    {% csrf_token %}
                  <div class="row">
                    <div class="col-md-12">
                      <h4 class="title mt15">Leave a Reply</h4>
                      <div class="form-group">
                        <label class="heading-color mb10">Your review</label>
                        <textarea name="comment" class="form-control" rows="6"></textarea>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="heading-color mb10">Name</label>
                        <input name="full_name" type="text" class="form-control">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="heading-color mb10">Email</label>
                        <input name="email" type="email" class="form-control">
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                        <label class="form-check-label" for="defaultCheck1">Save my name, email, and website in this browser for the next time I comment.</label>
                      </div>
                      <br>
                      <button type="submit" class="btn purple-btn" style="color:#fff;">Submit</button>
                    </div>
                  </div>
                </form>
              </div>
            <div class="product_single_content mb30">
              <div class="mbp_pagination_comments">
                <h5 class="mb30">Comments ({{comment.count}})</h5>
                
                {% for c in comment %}
                   <div class="shadow p-3" style="border-radius: 10px;">
                    <div class="mbp_first d-flex align-items-center mb20">
                        <div class="flex-shrink-0"> <img src="{{post.user.profile.image.url}}" style="width: 50px; height: 50px; object-fit: cover; border-radius: 50%;" class="mr-3" alt="{{c.full_name|title}}"> </div>
                        <div class="flex-grow-1 ms-4">
                            <div class="d-block d-md-flex">
                                <h5 class="sub_title">{{c.full_name|title}}</h5>
                            </div>
                            <div class="review_post_meta">{{c.date|date:"d M, Y"}}</div>
                        </div>
                        </div>
                        <div class="review_content_para mb30">
                        <p class="mt15 mb30">{{ c.comment }}</p>
                        </div>
                        <div class="review_cansel_btns d-flex mb30">
                        <!-- <a href="#" class="btn">Report abuse</a> -->
                        </div>
                   </div>
                {% empty %}
                <div>
                    <h3>No Comments Yet</h3>
                </div>
                {% endfor %}
               
              </div>
            </div>
            <hr>
            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <h3 class="mb50 mt30">Related Articles</h3>
        </div>
        {% for p in related_blogs %}
            <div class="col-sm-6 col-lg-4 border p-1">
            <div class="for_blog">
                <div class="thumb">
                <img class="img-whp" src="{{p.image.url}}" style="width: 100%; height: 150px; object-fit: cover; border-radius: 10px;" alt="1.jpg">
                </div>
                <div class="details">
                <div class="tc_content">
                    <span class="subtitle">{{p.category.title}}</span>
                    <h4 class="title"><a href="{% url 'blog:blog-detail' p.pid %}">Collar brings back coffee brewing ritual</a></h4>
                    <span class="post_date">{{p.date|date:"d M, Y"}}</span> <br>
                    <a href="{% url 'blog:blog-detail' p.pid %}" class="purple-btn btn mt-3">Read More</a>

                </div>
                </div>
            </div>
            </div>
        {% empty %}
        <div>
            <h3>No Related Posts Yet...</h3>
        </div>
        {% endfor %}
        
      </div>
    </div>
  </section>
  {% endblock content %}

templates/blog/post-lists.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
  
  <section class="inner_page_breadcrumb">
    <div class="container">
      <div class="row">
        <div class="col-xl-6">
          <div class="breadcrumb_content">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page"><a>Blog Posts</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

	<section class="blog_post_container pt30 pb80">
		<div class="container">
      <div class="row">
        <div class="col-lg-6 m-auto">
          <div class="main-title text-center">
            
            {% if query == "" or query == None %}
            <h2 class="title">Trending Posts 🔥</h2>
            {% else %}
            <h2 class="title">Showing Results for "{{query}}"</h2>
            {% endif %}
                
          </div>
        </div>
      </div>
			<div class="row mt50">
        <div class="col-lg-4 col-xl-3">
          <div class="sidebar_search_widget mb30">
            <form action="" method="GET">
                <div class="blog_search_widget">
                    <div class="input-group">
                      <input name="q" type="text" class="form-control" placeholder="Search Articles..." aria-label="Recipient's username">
                      <button style="border: 1px solid rgba(128, 128, 128, 0.247); background: none;"><i class="fas fa-search"></i></button>
                    </div> 
                  </div>
            </form>
          </div>
          <div class="terms_condition_widget">
            <h4 class="title">Categories</h4>
            <div class="widget_list">
              <ul class="list_details">
                {% for c in categories %}
                    <li><a href="{% url 'blog:category_detail' c.slug %}">{{c.title}}</a></li>
                {% endfor %}
                
              </ul>
            </div>
          </div>
          <div class="sidebar_feature_listing">
            <h4 class="title">Featured Posts</h4>
            {% for p in featured_blog %}
            <a href="{% url 'blog:blog-detail' p.pid %}">
            <div class="d-flex shadow p-2 mb-3 mt-1" style="border-radius: 8px;">
              <div class="flex-shrink-0">
                <img class="align-self-start mr-3" src="{{p.image.url}}" style="width: 40px; height: 40px; object-fit: cover;" alt="s1.jpg">
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="post_title">{{p.title|truncatechars:27}}</a></h5>
                <a href="{% url 'blog:blog-detail' p.pid %}">{{p.date|date:"d M, Y"}}
              </div>
            </div>
            </a>
            {% endfor %}
          </div>
        </div>
				<div class="col-lg-8 col-xl-9">
          <div class="row">
            {% for p in blog %}
            <div class="col-md-6 col-xl-4">
              <div class="for_blog">
                <div class="thumb">
                  <img class="img-whp" src="{{p.image.url}}" style="width: 100%; height: 240px; object-fit: cover;" alt="{{p.title}}">
                </div>
                <div class="details">
                  <div class="tc_content">
                    <span class="subtitle">{{p.category.title}}</span>
                    <h4 class="title"><a href="{% url 'blog:blog-detail' p.pid %}">{{p.title|truncatechars:60}}</a></h4>
                    <span class="post_date">{{p.date|date:"d M, Y"}}</span> <br>
                    <a href="{% url 'blog:blog-detail' p.pid %}" class="purple-btn btn mt-3">Read More</a>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            
          </div>
          <div class="row">
            <div class="col-lg-12">
              <div class="mbp_pagination mt30 text-center">
                <ul class="page_navigation">
                  {% if blog.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="{% url 'blog:blog-list' %}?page={{blog.previous_page_number}}" tabindex="-1" aria-disabled="true"> <span class="fas fa-angle-left"></span></a>
                    </li>
                {% endif %}
                
                {% if blog.has_next %}
                    <li class="page-item">
                    <a class="page-link" href="{% url 'blog:blog-list' %}?page={{blog.next_page_number}}"><span class="fas fa-angle-right"></span></a>
                    </li>
                {% endif %}
                </ul>
                <p class="mt20 pagination_page_count text-center">{{blog_count.count}} Article(s) Found</p>
              </div>
            </div>
          </div>
				</div>
			</div>
		</div>
	</section>

    {% endblock content %}