blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

ecommerce_prj/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

templates/buyer/address-edit.html
{% extends "partials/base.html" %} {% load static %} 
{% block title %}
  Edit Address
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<section class="oufr-log-rfeg bgcf-f5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xl-12 col-xxl-12 m-auto">
        <div class="log_reg_form mt70-992">
          <h2 class="title">Update Address</h2>
          <div class="login_form">
            <form method="POST">
              {% csrf_token %}
              <div class="mb-2 mr-sm-2">{{form.as_p}}</div>

              <button type="submit" class="btn purple-btn btn-thm">Save Update</button>
              <a href="{% url 'core:buyer-address' %}" class="btn btn-secondary">Go Back</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/dashboard.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}
  Dashboard
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<section class="our-dashbord dashbord"style="margin-top: 0;">
   <div class="container">
      <div class="row">
         {% include 'buyer/nav-desktop.html' %}
         <div class="col-lg-9 col-xl-9">
            {% include 'buyer/nav-mobile.html' %}
               <div class="row">
               <div class="col-xl-12">
                  <div class="account_user_deails pl40 pl0-md">
                     <h2 class="title mb30">My Dashboard</h2>
                     <div class="ui_kit_tab style2">
                        <!-- nav tab Nav List Start -->
                        <ul class="nav nav-tabs mb15" id="myTab" role="tablist">
                           <li class="nav-item" role="presentation">
                              <button class="nav-link active" id="t20-tab" data-bs-toggle="tab" data-bs-target="#t20" type="button" role="tab" aria-controls="t20" aria-selected="true">Order Analytics</button>
                           </li>
                           
                        </ul>
                        <!-- nav tab Nav List End -->
                        <!-- nav tab contents Start -->
                        <div class="tab-content pt20 row" id="myTabContent">
                           <div class="tab-pane fade show active col-lg-12" id="t20" role="tabpanel" aria-labelledby="t20-tab">
                              <div class="account_details_page form_grid">
                                 <canvas id="myChartJs" style="height:230px;"></canvas>
                              </div>
                           </div>
                           
                        </div>
                        <!-- nav tab contents End -->
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <script type="text/javascript">
    const labels = {{monthNumber|safe}};
    const data = {
      labels: labels,
      datasets: [{
        label: 'Orders',
        backgroundColor: '#b331ff ',
        borderColor: '#b331ff',
        data: {{totalOrders}},
      }]
    };
  
    const config = {
      type: 'line',
      data,
      options: {
        responsive: true
      }
    };
  
    var myChart = new Chart(
        document.getElementById('myChartJs'),
        config
      );
  
  </script>

{% endblock content %}

templates/buyer/invoices.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}
  Invoices
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<section class="our-dashbord dashbord">
  <div class="container">
    <div class="row">
      {% include 'buyer/nav-desktop.html' %}
      <div class="col-lg-9 col-xl-9">
        {% include 'buyer/nav-mobile.html' %}
        <div class="row">
          <div class="col-xl-12">
            <div class="account_user_deails pl40 pl0-md">
              <h2 class="title mb30">My Invoices</h2>
              <div class="ui_kit_tab style2">
                <!-- nav tab Nav List Start -->
                <div class="tab-content pt20 row" id="myTabContent">
                  <div class="tab-pane fade show active col-lg-12" id="t20" role="tabpanel" aria-labelledby="t20-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light" id="">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for i in invoices %}
                            <tr>
                              <th scope="row">{{i.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{i.date}}</small></td>
                              <td class="text-success">{{i.payment_status|title}}</td>
                              <td>{{ cs }}{{ i.total }}</td>
                              <td class="statufs"><span class="style4"><a
                                    href="{% url 'core:buyer-invoice-detail' i.oid %}"><i class="fas fa-eye">
                                    </i></a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-lg-12" id="baby" role="tabpanel" aria-labelledby="baby-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Shipped</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in shipped %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">View Detail</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-xl-12" id="furniture" role="tabpanel" aria-labelledby="furniture-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Delivered Orders</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in collected %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">View Detail</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>

                  </div>
                </div>
                <!-- nav tab contents End -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/messages.html
{% extends "partials/base.html" %} 
{% load static %} {% load crispy_forms_tags %} 
{% block title %}
  Messages
{% endblock title %}
{% block content %}
<section class="our-dashbord dashbord" style="margin-top: 80px">
  <div class="container">
    <div class="row">
      {% include 'buyer/nav-desktop.html' %}
      <div class="col-lg-9 col-xl-9">
        {% include 'buyer/nav-mobile.html' %}
        <div class="row">
          <div class="col-xl-12">
            <div class="account_user_deails pl40 pl0-md">
              <div class="ui_kit_tab style2">
                <div class="row pb50">
                  <div class="col-lg-12">
                    <div class="dashboard_title_area">
                      <h2>Messages</h2>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-12 col-xxl-12">
                    <div class="message_container">
                      <div class="inbox_user_list">
                        <div class="iu_heading">
                          <div class="candidate_revew_search_box">
                            <form
                              class="row-cols-lg-aufto g-3 align-items-center d-flex p-3 m-2"
                              action="{% url 'core:search_users' %}"
                              method="GET"
                            >
                              <input
                                class="form-control"
                                type="search"
                                name="q"
                                placeholder="Search For Someone..."
                                aria-label="Search"
                              />
                              <button class="btn border p-2 ms-2" type="submit">
                                <span class="fas fa-search"></span>
                              </button>
                            </form>
                          </div>
                        </div>
                        <ul class="p-3">
                          {% for message in messagess %} {% if request.user == message.sender %}
                          <a
                            href="{% url 'core:inbox-detail' message.reciever.username %}"
                          >
                            <li class="contact pt3">
                              <div
                                class="wrap shadow p-3"
                                style="border-radius: 10px"
                              >
                                <img
                                  class="img-fluid"
                                  src="{{message.reciever.profile.image.url}}"
                                  style="
                                    width: 50px;
                                    height: 50px;
                                    object-fit: cover;
                                  "
                                  alt="ms1.jpg"
                                />

                                <div class="child-wrap df">
                                  <div class="meta">
                                    {% if message.reciever.profile.full_name %}
                                    <h5 class="name">
                                      {{message.reciever.profile.full_name|title}}
                                    </h5>
                                    {% else %}
                                    <h5 class="name">
                                      {{message.reciever.username|title}}
                                    </h5>
                                    {% endif %}
                                    <p class="preview">
                                      {{message.message|truncatechars:27}}
                                    </p>
                                  </div>
                                  <div class="iul_notific">
                                    <small class="body-color"
                                      >{{message.date|timesince}} ago</small
                                    >
                                  </div>
                                </div>
                              </div>
                            </li>
                          </a>
                          {% endif %} 
                          {% if request.user == message.reciever %}
                          <a
                            href="{% url 'core:inbox-detail' message.sender.username %}"
                          >
                            <li class="contact pt3">
                              <div
                                class="wrap shadow p-3"
                                style="border-radius: 10px"
                              >
                                <img
                                  class="img-fluid"
                                  src="{{message.sender.profile.image.url}}"
                                  style="
                                    width: 50px;
                                    height: 50px;
                                    object-fit: cover;
                                  "
                                  alt="ms1.jpg"
                                />
                                <div class="child-wrap df">
                                  <div class="meta">
                                    {% if message.sender.profile.full_name %}
                                    <h5 class="name">
                                      {{message.sender.profile.full_name|title}}
                                    </h5>
                                    {% else %}
                                    <h5 class="name">
                                      {{message.sender.username|title}}
                                    </h5>
                                    {% endif %}
                                    <p class="preview">
                                      {{message.message|truncatechars:27}}
                                    </p>
                                  </div>
                                  <div class="iul_notific">
                                    <small class="body-color"
                                      >{{message.date|timesince}} ago</small
                                    >
                                  </div>
                                </div>
                              </div>
                            </li>
                          </a>
                          {% endif %} {% empty %}
                          <h4>No Chats Yet...</h4>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/nav-mobile.html
<style>
   ul,li{
      list-style: none;
   }
</style>
<div class="row" style="margin-top: 140px;">
   <!-- style="margin-top: 100px;" -->
    <div class="col-lg-12">
      
       <div class="dashboard_navigationbar dn db-md " style="margin-top: -100px;">
         <div class="account_details_user d-flex pb10 bb1 mb10 shadow p-3" style="border-radius: 10px;">
            <img class="me-3" src="{{request.user.profile.image.url}}" style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover;" alt="Generic placeholder image">
            <div class="content_details text-start">
               
               {% if request.user.profile.full_name %}
               <h5 class="title">{{request.user.profile.full_name|title}}</h5>
               {% else %}
               <h5 class="title">{{request.user.username|title}}</h5>
               {% endif %}
                  
               <a class="stitle" >{{request.user.email}}</a> <br>
               <a class="stitle" >Account ID: <b><i>{{request.user.id}}</i></b></a>

            </div>
         </div>
          <div class="dropdown">
             <button onclick="myFunction()" class="dropbtn"><i class="fas fa-bars pr10"></i> Dashboard Navigation</button>
             <ul id="myDropdown" class="dropdown-content">
                <li><a class="active" href="{% url 'core:buyer-dashboard' %}"><span class="bi bi-grid-3x3-gap-fill"></span>Dashboard</a></li>
                <li><a class="active" href="{% url 'core:profile' %}"><span class="fas fa-user"></span>Account Details</a></li>
                <li><a href="{% url 'core:buyer-orders' %}"><span class="fas fa-list"></span>Order</a></li>
                <li><a href="{% url 'core:buyer_bids' %}"><span class="fas fa-chart-simple"></span>My Bids</a></li>
                <li><a href="{% url 'core:buyer_offer' %}"><span class="bi bi-shop"></span>My Offers</a></li>
                <li><a href="{% url 'core:buyer_message' %}"><span class="bi bi-chat-right-dots-fill"></span>Message</a></li>
                <li><a href="{% url 'core:buyer-address' %}"><span class="fas fa-location"></span>Address</a></li>
                <li><a href="{% url 'core:buyer-wishlist' %}"><span class="fas fa-heart"></span>Wishlist</a></li>
                <li><a href="{% url 'core:buyer-invoices' %}"><span class="fas fa-file-invoice"></span>Invoices</a></li>
                <li><a href="{% url 'core:settings' %}"><span class="bi bi-gear-fill"></span>Settings</a></li>
                <li><a href="{% url 'userauths:sign-out' %}"><span class="fas fa-right-from-bracket"></span>Logout</a></li>
             </ul>
          </div>
          
       </div>
    </div>
 </div>

templates/buyer/search_user.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}
  Search Users
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<section class="our-dashbord dashbord">
  <div class="container">
    <div class="row">
      {% include 'buyer/nav-desktop.html' %}
      <div class="col-lg-9 col-xl-9">
        {% include 'buyer/nav-mobile.html' %}
        <div class="row">
          <div class="col-xl-12">
            <div class="account_user_deails pl40 pl0-md">
              <div class="ui_kit_tab style2">
                <div class="row pb50">
                  <div class="col-lg-12">
                    <div class="dashboard_title_area">
                      <h2>Messages</h2>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-12 col-xxl-12">
                    <div class="message_container">
                      <div class="inbox_user_list">
                        <div class="iu_heading">
                          <div class="candidate_revew_search_box">
                            <form class="row-cols-lg-aufto g-3 align-items-center d-flex p-3 m-2" action="{% url 'core:search_users' %}" method="GET">
                                {% csrf_token %}
                                <input class="form-control" type="search" name="q" placeholder="Search For Someone..." aria-label="Search">
                                <button class="btn border p-2 ms-2"  type="submit"><span class="fas fa-search"></span></button>
                              </form>
                          </div>
                        </div>
                        <div class="row">
                        </div>
                        <ul>
                            <h4 class="p-3">Showing Results for "{{query}}"</h4>
                            {% for message in users %}
          
                            <a href="{% url 'core:inbox-detail' message.username %}">
                              <li class="contact pt3 p-3">
                                <div class="wrap shadow p-4" style="border-radius: 10px">
                                  <img
                                    class="img-fluid"
                                    src="{{message.profile.image.url}}"
                                    style="width: 40px; height: 40px; object-fit: cover"
                                    alt="ms1.jpg"
                                  />
                                  <div class="child-wrap df">
                                    <div class="meta">
                                      {% if message.profile.full_name %}
                                      <h5 class="name">
                                        {{message.profile.full_name|title}}
                                      </h5>
                                      {% else %}
                                      <h5 class="name">{{message.username|title}}</h5>
                                      {% endif %}
                                      <p class="preview">
                                        Send Message
                                        <i class="bi bi-chat-right-dots-fill"></i>
                                      </p>
                                    </div>
                                    <div class="iul_notific">
                                      <small class="body-color"></small>
                                    </div>
                                  </div>
                                </div>
                              </li>
                            </a>
          
                            {% empty %}
                            <h4>No Users Found...</h4>
                            {% endfor %}
                          </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}